---

#- name:         get the list of Logstash templates to transfer
#  local_action: "shell ls {{item}}/* | sed 's~.*/~~g'"
#  tags: logstash_config_files
#  register:     template_files_Logstash
#  with_items: logstash_config_files
- name: debug items
  debug: var=item
  tags: logstash_config_files
  with_fileglob:
    - "{{ item }}/*"
  with_items:
    - "{{ logstash_config_files }}"

- name: Copy Logstash template config files
  template: src={{ item }}
            dest={{ logstash_conf_dir }}/
            validate="{{ logstash_home_dir }}/bin/logstash agent -t -f %s"
  register: template_files_Logstash
  with_fileglob:
    - "{{ item }}/*"
  with_items:
    - "{{ logstash_config_files }}"
  notify:
   - restart logstash
  tags: logstash_config_files
  when: logstash_config_files is defined

 # cLEAN AND DELETE UNMANGED FILES

- shell: ls -1 {{ logstash_conf_dir }}
  register: logstash_conf_contents
  tags: logstash_config_files
- name: Removing unmanaged files from logstash config dir
  file: path={{ logstash_conf_dir }}/{{ item }} state=absent
#  debug: msg="Removing {{ item }}"
  with_items: logstash_conf_contents.stdout_lines
  when: item not in (template_files_Logstash + ["00-ansible-gen-input.conf" ,"51-ansible-gen-filters.conf", "99-ansible-gen-output.conf" ])
  tags: logstash_config_files

- name: Copy Logstash Input Configuration
  template: src=input.conf.j2
            dest={{ logstash_conf_dir }}00-ansible-gen-input.conf
            owner=root 
            group=root 
            mode=0644
            validate="{{ logstash_home_dir }}/bin/logstash agent -t -f %s"
  notify:
   - restart logstash
  tags: logstash_inputs
  when: logstash_inputs is defined

- name: Copy Logstash Filter Configuration
  template: src=filters.conf.j2
            dest={{ logstash_conf_dir }}51-ansible-gen-filters.conf
            owner=root 
            group=root 
            mode=0644
            validate="{{ logstash_home_dir }}/bin/logstash agent -t -f %s"
  notify:
   - restart logstash
  tags: logstash_filters
  when: logstash_filters is defined

- name: Copy Logstash Output Configuration
  template: src=output.conf.j2
            dest={{ logstash_conf_dir }}99-ansible-gen-output.conf
            owner=root 
            group=root 
            mode=0644
            validate="{{ logstash_home_dir }}/bin/logstash agent -t -f %s"
  notify:
   - restart logstash
  tags: logstash_outputs
  when: logstash_outputs is defined

